name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true  # 必须开启！因为你有 Sass/Dart

      - name: Build Web
        run: hugo --gc --minify

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v4
        with:
          PERSONAL_TOKEN: ${{ secrets.HUGO_DEPLOY_TOKEN }}
          PUBLISH_BRANCH: gh-pages # 建议发布到 gh-pages 分支，保持 main 分支是源码
          PUBLISH_DIR: ./public
          commit_message: "自动部署: ${{ github.event.head_commit.message }}"